services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    JobsBundle\Registry\ContextItemsResolverRegistryInterface: '@JobsBundle\Registry\ContextItemsResolverRegistry'
    JobsBundle\Registry\ContextItemsResolverRegistry: ~

    JobsBundle\Context\Resolver\DynamicRouteRequestResolver:
        tags:
            - {name: jobs.context.items_resolver, identifier: dynamic_route_request}

    JobsBundle\Context\Resolver\PimcoreObjectResolver:
        tags:
            - {name: jobs.context.items_resolver, identifier: pimcore_object}

    JobsBundle\Context\Resolver\SeoQueueResolver:
        tags:
            - {name: jobs.context.items_resolver, identifier: seo_queue}

    JobsBundle\Context\Resolver\FeedResolver:
        tags:
            - {name: jobs.context.items_resolver, identifier: feed}