services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    JobsBundle\EventListener\Admin\AssetListener:
        tags:
            - { name: kernel.event_subscriber }

    JobsBundle\Connector\ConnectorServiceInterface: '@JobsBundle\Connector\ConnectorService'
    JobsBundle\Connector\ConnectorService: ~

    JobsBundle\Context\ContextServiceInterface: '@JobsBundle\Context\ContextService'
    JobsBundle\Context\ContextService: ~

    JobsBundle\Service\LinkGeneratorServiceInterface: '@JobsBundle\Service\LinkGeneratorService'
    JobsBundle\Service\LinkGeneratorService: ~

    JobsBundle\Service\EnvironmentServiceInterface: '@JobsBundle\Service\EnvironmentService'
    JobsBundle\Service\EnvironmentService: ~

    JobsBundle\Normalizer\EntityNormalizer:
        tags:
            - serializer.normalizer

    jobs.internal.serializer:
        alias: serializer
        public: true