JobsBundle\Model\ConnectorContextItem:
    attributes:
        id:
            groups: [ Default, Version ]
        objectId:
            groups: [ Default, Version ]
        connectorEngine:
            groups: [ Default, Version ]
        contextDefinition:
            groups: [ Default, Version ]
