services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    JobsBundle\Seo\ResourceProcessor\GoogleJobsProcessor:
        tags:
            - { name: seo.index.resource_processor, identifier: google_jobs }

    JobsBundle\Seo\Extractor\GoogleForJobsExtractor:
        tags:
            - {name: seo.meta_data.extractor, identifier: google_jobs_extractor }
