services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    JobsBundle\Seo\ResourceProcessor\GoogleJobsProcessor:
        tags:
            - { name: seo.index.resource_processor, identifier: google_jobs }