pimcore:
    objects:
        class_definitions:
            data:
                map:
                    jobConnectorContext: JobsBundle\CoreExtension\JobConnectorContext

doctrine:
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                auto_mapping: true

doctrine_migrations:
    migrations_paths:
        'JobsBundle\Migrations': '@JobsBundle/Migrations'
