# Admin Routes
jobs_admin_settings_connectors:
    path: /admin/jobs/settings/get-connectors
    defaults: { _controller: JobsBundle\Controller\Admin\SettingsController::getConnectorsAction }

jobs_admin_settings_data_class_health_check:
    path: /admin/jobs/settings/data-class-health-check
    defaults: { _controller: JobsBundle\Controller\Admin\SettingsController::dataClassHealthCheckAction }

jobs_admin_settings_connector_install:
    path: /admin/jobs/settings/install-connector/{connectorName}
    defaults: { _controller: JobsBundle\Controller\Admin\SettingsController::installConnectorAction }

jobs_admin_settings_connector_uninstall:
    path: /admin/jobs/settings/uninstall-connector/{connectorName}
    defaults: { _controller: JobsBundle\Controller\Admin\SettingsController::uninstallConnectorAction }

jobs_admin_settings_change_connector_state:
    path: /admin/jobs/settings/change-connector-type/{connectorName}/{stateType}/{flag}
    defaults: { _controller: JobsBundle\Controller\Admin\SettingsController::changeConnectorStateAction }

jobs_admin_settings_save_connector_configuration:
    path: /admin/jobs/settings/save-connector-configuration/{connectorName}
    methods: [POST]
    defaults: { _controller: JobsBundle\Controller\Admin\SettingsController::saveConnectorConfigurationAction }

jobs_admin_settings_list_context_definitions:
    path: /admin/jobs/settings/list-context-definitions
    methods: [GET]
    defaults: { _controller: JobsBundle\Controller\Admin\SettingsController::listContextDefinitionsAction }

jobs_admin_settings_create_context_definition:
    path: /admin/jobs/settings/create-context-definition
    methods: [POST]
    defaults: { _controller: JobsBundle\Controller\Admin\SettingsController::createContextDefinitionAction }

jobs_admin_settings_delete_context_definition:
    path: /admin/jobs/settings/delete-context-definition
    methods: [DELETE]
    defaults: { _controller: JobsBundle\Controller\Admin\SettingsController::deleteContextDefinitionAction }

jobs_admin_settings_list_feed_ids:
    path: /admin/jobs/settings/list-feed-ids/{connectorName}
    methods: [GET]
    defaults: { _controller: JobsBundle\Controller\Admin\SettingsController::listFeedIdsAction }

# Provider Routes
jobs_provider_feed:
    path: /jobs/{connectorName}/{token}/feed/{feedId}
    defaults: { _controller: JobsBundle\Controller\ProviderController::provideFeedAction }

# Connector Specific Routes
jobs_facebook_connect:
    path: /jobs/facebook/{token}/connect
    defaults: { _controller: JobsBundle\Controller\FacebookController::connectAction }

jobs_facebook_connect_check:
    path: /jobs/facebook/{token}/check
    defaults: { _controller: JobsBundle\Controller\FacebookController::checkAction }

jobs_facebook_generate_feed:
    methods: [POST]
    path: /admin/jobs/facebook/generate-feed
    defaults: { _controller: JobsBundle\Controller\FacebookController::adminGenerateFeedAction }