pimcore:
    objects:
        class_definitions:
            data:
                map:
                    jobConnectorContext: JobsBundle\CoreExtension\JobConnectorContext

doctrine_migrations:
    migrations_paths:
        'JobsBundle\Migrations': '@JobsBundle/src/Migrations'
