services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    JobsBundle\Connector\ConnectorService: ~
    JobsBundle\Connector\ConnectorServiceInterface: '@JobsBundle\Connector\ConnectorService'

    JobsBundle\Registry\ConnectorRegistry: ~
    JobsBundle\Registry\ConnectorRegistryInterface: '@JobsBundle\Registry\ConnectorRegistry'

    JobsBundle\Connector\Google\Connector:
        tags:
            - {name: jobs.connector, identifier: google}

    JobsBundle\Connector\Facebook\Connector:
        tags:
            - {name: jobs.connector, identifier: facebook}