services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    JobsBundle\Tool\Install:
        arguments:
            $bundle: "@=service('kernel').getBundle('JobsBundle')"
