services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    JobsBundle\Manager\ConnectorManagerInterface: '@JobsBundle\Manager\ConnectorManager'
    JobsBundle\Manager\ConnectorManager:
        arguments:
            $availableConnectors: '%jobs.connectors.available%'

    JobsBundle\Manager\ConnectorContextManagerInterface: '@JobsBundle\Manager\ConnectorContextManager'
    JobsBundle\Manager\ConnectorContextManager:
        public: true # required in coreExtensions

    JobsBundle\Manager\ContextDefinitionManagerInterface: '@JobsBundle\Manager\ContextDefinitionManager'
    JobsBundle\Manager\ContextDefinitionManager: ~

    JobsBundle\Manager\LogManagerInterface: '@JobsBundle\Manager\LogManager'
    JobsBundle\Manager\LogManager:
        public: true # required in coreExtensions
