services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    JobsBundle\Repository\ConnectorEngineRepositoryInterface: '@JobsBundle\Repository\ConnectorEngineRepository'
    JobsBundle\Repository\ConnectorEngineRepository: ~

    JobsBundle\Repository\ConnectorContextItemRepositoryInterface: '@JobsBundle\Repository\ConnectorContextItemRepository'
    JobsBundle\Repository\ConnectorContextItemRepository: ~
